### ISSUE TITLE
Progamatic input of values

### ISSUE THREAD

**Issue by elyobelyob** [bartbutenaers/node-red-contrib-msg-resend#1]
Many thanks for this, it's great, as my cloud based light controller can need a couple of sends occasionally.

As a wish list, it's be useful to feed in the number of resends via a msg variable. Probably the repeat time as well. 

I've added an extra MQTT topic level to my commands to let it know that it needs a repeat e.g. from action/telldus/onOffDevice/669968/1 to action/telldus/onOffDevice/669968/1/3 ... which tells my system to switch on the device and it'd be useful to feed in that last variable to repeat three times.

Thanks again.

**Comment by bartbutenaers** [comment]
Hey Elyobelyob,

I will try to add this kind of behaviour this week to the node.
A control message should have following fields I assume:

- resend_interval (seconds)
- resend_max_count (number)
- resend_force_clone (boolean to force cloning)
- resend_abort (if 'true' the current timer will be aborted, so resending the last message stops.  If 'false' the current timer will continue, with the new repeat_time/resend_count)
- resend_skip (if 'true' this message will not be resend.  Could be used to skip resending control messages from being resend).

I will keep you infomed when a new version is available.

Kind regards,
Bart

**Comment by bartbutenaers** [comment]
Hey @elyobelyob,

I have released version 0.0.5, allowing to control the msg-resend node via message properties.  At the end of the readme.md file, a new section is available with a description of the msg control properties.  

Could you please let me know if this is sufficient for your implementation?

Kind regards,
Bart

**Comment by elyobelyob** [comment]
Bart, I was jaw droppingly amazed to see that so fast. And to such a well
thought out level (far beyond what I asked for!).

It took a little while o update my main server, so will know in 24 hours
whether it's worked. But from what I can see, yes, yes it will.

Thanks very much!

Regards

Nick
